# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e20e7d7504b59cea0915f300b9a9c4f3075d8a419f0d8400d20cc1ced4ad67dfd26f8a3178e0b736e336b7448159359884073573723301b6bdaf5507662e079b

test:
  secret_key_base: 9ff20488f6aa1e3a44f44effe3020ab3bcbf046ef37eb74c85e30972c123574e4532192a8ec21d48396f19089989d4dfdd38847156975dd6ba4bc71e00c187e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
